name = "StaTech Industry"
author = "static"
version = "1.1.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48f7e8e5b5e4f77b1c88bb5493bc86e4e4063fef18e826951bc267a40577c09c"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
