# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				cow = true
				chicken = true
				pig = true
				item = true
				experience_orb = true
				lightning_bolt = true
				bat = true
				glow_squid = true
				item_frame = true
				armor_stand = true
				painting = true
				zombie = true
				cave_spider = true
				skeleton = true
				creeper = true
				ender_dragon = true
				enderman = true
				phantom = true
				fox = true
				wolf = true
				spider = true
				axolotl = true
				squid = true
				zombie_villager = true
				sheep = true

			[light_sources.settings.entities.naturalist]
				snake = true
				butterfly = true
				robin = true
				firefly = true
				duck = true
				bluejay = true

			[light_sources.settings.entities.ecologics]
				squirrel = true
				penguin = true

			[light_sources.settings.entities.goblintraders]
				goblin_trader = true

			[light_sources.settings.entities.spectrum]
				shooting_star = true
				lizard = true
				phantom_frame = true
				preservation_turret = true

			[light_sources.settings.entities.promenade]
				lush_creeper = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.rottencreatures]
				undead_miner = true

